### ISSUE TITLE
timeline-icon alt= text gone?

### ISSUE THREAD

**Issue by mohawk2** [molly/web3-is-going-great#762]
Thank you for your entertaining and informative website! (And I assume the same code is used for the also-entertaining twitterisgoinggreat)

When I started looking at W3IGG a month or so ago, the various timeline icons had a hover-text. They now don't seem to, and e.g. the current top item (about Raydium) has `robber.png` as the icon, with this markup:

```
<div class="timeline-icon purple">
 <div class="icon-wrapper">
  <img src="https://storage.googleapis.com/primary-web3/icons/robber.png" alt="" aria-hidden="true">
 </div>
</div>
```

The `alt=""` doesn't look right to me, and the site used to have hovertext that explained the occasionally-inscrutable icons. If that's deliberate, then so be it, and sorry to have bothered you.

**Comment by molly** [comment]
That `alt=""` has been there for a long time—it's to avoid screenreaders being overly verbose with decorative-only components. That said, the tooltips you describe do sound useful, so I've added them in!

**Comment by mohawk2** [comment]
Sorry for my confusion - the other prompt for opening this issue was that on TIGG has icons, which I seem to remember previously having tooltips. The current top item: 

```html
<div class="timeline-entry timeline-entry--visible" data-category="No-One Minding the Store" aria-hidden="false">
 <div class="timeline-icon timeline-icon--blue">
  <span class="icon-wrapper pass-pointer-events">
   <svg>[snip]</svg>
  </span>
 </div>
 [snip]
</div>
```

It seems to me this `timeline-icon` should have a tooltip "No-One Minding the Store"?

**Comment by molly** [comment]
Oh! I clearly did not read the original issue closely enough, sorry!

TIGG is forked from my other project, https://github.com/molly/static-timeline-generator. This project uses a similar design but has diverged considerably from that project's source because it needs some quite custom features and also uses a more robust backend.

I'll backfill this change into the static-timeline-generator repo because I do think it's a valuable change, but I'm not sure if the TIGG folks are keeping their project up-to-date with the upstream. They have contact info at the bottom of their site if you wanted to reach out and suggest the change to them, though I don't think they have the project source on Github anymore.

**Comment by mohawk2** [comment]
Ahh, I thought it was you! I will ping them.
