### ISSUE TITLE
[NEW]: Elon Musk facing 258 billion $ raketeering lawsuit for Dogecoin

### ISSUE THREAD

**Issue by NHOrus** [molly/web3-is-going-great#910]
### Date

2023-04-03

### Description

Investors accused Musk, the world's second-richest person according to Forbes, of deliberately driving up Dogecoin's price more than 36,000% over two years and then letting it crash.

### Links

https://www.reuters.com/legal/elon-musk-seeks-end-258-billion-dogecoin-lawsuit-2023-04-01/

### Agreement

- [X] I irrevocably agree to release my contribution under the CC-BY 3.0 License

### Attribution name

@NHOball

**Comment by molly** [comment]
Just leaving a note that I'm aware of this, but holding off on posting until the motion to dismiss is considered. If the judge rejects the motion, I'll probably post it. Class actions are so tricky — there are so many of them that I'm still trying to establish a good metric on when to include them on the site.

**Comment by paulehoffman** [comment]
It is factual to say that he was sued. It is factual to say that he is requesting the suit be dismissed. The former is newsworthy; the latter will always happen and thus is not itself newsworthy. Unfortunately, a judge letting the suit proceed is not newsworthy because the amount in the suit is not relevant: the judge could let it go ahead knowing that the likely judgement or settlement is 1% of the asked-for amount.
